version: '3'
services:
  service:
    build: ./
    ports:
      - ${SERVER_PORT}:8080
    depends_on:
      - postgres
    command: ./service
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}

      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}

  postgres:
    image: postgres:16
    expose:
      - "5432"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./migration.sql:/docker-entrypoint-initdb.d/migration.sql
    restart: always
    healthcheck:
      test: "exit 0"
